name: groshop
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependency_overrides:
  intl: ^0.17.0-nullsafety.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.0
  intl: ^0.16.0
  percent_indicator: ^2.1.5
  flutter_rating_bar: ^3.0.1+1
  flutter_phoenix: ^0.1.0
  flutter_bloc: ^6.0.1
  grouped_buttons: ^1.0.4
  carousel_slider: ^2.2.1
  firebase_core : ^0.5.0
  firebase_auth: ^0.18.4+1
  flutter_local_notifications: ^2.0.0
  firebase_messaging: ^7.0.2
  shared_preferences: ^0.5.10
  toast: ^0.1.5
  http: ^0.12.2
  flutter_facebook_login: ^3.0.0
  google_sign_in: ^4.5.9
  flutter_barcode_scanner: ^1.0.2
  image_picker: ^0.6.7+11
  shimmer_animation: ^0.1.1
  flutter_html: ^1.1.1
  cached_network_image: ^2.5.0
  geolocator: ^6.0.0+4
  geocoder: ^0.2.1
  google_maps_flutter: ^1.0.3
  google_place: ^0.3.3
  google_maps_webservice: ^0.0.19
  mapbox_search: ^2.1.0
  horizontal_calendar_widget: ^1.0.2
  http_auth: ^0.3.1
  flutter_paystack: ^1.0.4+1
  stripe_payment: ^1.0.10
  flutter_credit_card: ^0.1.4
  marquee: ^1.7.0
  pdf: ^2.1.0
  flutter_full_pdf_viewer: ^1.0.6
  path_provider: ^1.6.27
  printing: ^4.1.0
  flutter_share: ^1.0.2+1
#  stripe_sdk: ^4.0.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^3.4.1
  intl_translation: ^0.17.9
  flutter_launcher_icons: ^0.8.1
  change_app_package_name: ^0.1.2
  razorpay_flutter: ^1.2.3

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  fonts:
     - family: ProductSans
       fonts:
         - asset: fonts/ProductSans-Regular.ttf
         - asset: fonts/ProductSans-Bold.ttf


  assets:
    - assets/
    - assets/ProductImages/
    - assets/PaymentIcons/
    - assets/CategoryImages/
    - assets/HomeBanner/
    - assets/fonts/OpenSans-Regular.ttf
    - assets/fonts/OpenSans-Bold.ttf
    - assets/fonts/OpenSans-Italic.ttf
    - assets/fonts/OpenSans-BoldItalic.ttf

